hikaya-io/activity

- activity/views.py
- templates/base.html
- templates/index.html
Move program add logic to own file
> ACT-45 Update Program Add Logic

- activity/settings/base.py
- activity/tokens.py
- activity/urls.py
- activity/views.py
- reports/views.py
- templates/registration/activate_email.html
- workflow/widgets.py
This PR Addresses sending a confirmation email to a new user after registration and enabling user to add Site and display charts in report
ACT-65: Add a token generator, and an activation function, with a HTML message to send in email
ACT-69, ACT-76: Go through code parts to find where the source of the error because it is not explicite in the debug errors
-
ACT-65,ACT-69,ACT-76
> Act-65 : Confirm email address + bugs fix (ACT-69, ACT-76)

- activity/settings/base.py
- activity/tokens.py
- activity/urls.py
- activity/views.py
- reports/views.py
- templates/registration/activate_email.html
- workflow/widgets.py
Reverts hikaya-io/Activity-CE#54
> Revert "Revert "Act-65 : Confirm email address + bugs fix (ACT-69, ACT-76)""

- templates/workflow/filter.html
- workflow/views.py
Fix bugs after UAT failed. ACT-71 and ACT-72
Check the source of the error. 
-
ACT-71,ACT-72
> ACT-71, ACT-72 : Stakeholder view (loading), program index view (list programs)

- static/css/app.css
- templates/customdashboard/program_list.html
- templates/formlibrary/beneficiary_list.html
- templates/formlibrary/distribution_list.html
- templates/formlibrary/training_list.html
- templates/index.html
- templates/indicators/collecteddata_list.html
- templates/indicators/data_report.html
- templates/indicators/disaggregation_report.html
- templates/indicators/report.html
- templates/indicators/tva_report.html
- templates/workflow/documentation_list.html
- templates/workflow/report.html
- templates/workflow/site_profile_list.html
- templates/workflow/stakeholder_list.html
Added subnavigation bar to all pages MVP.
@odenypeter, @henryohanga 
ACT-111
> Added subnavigation bar to all pages MVP

- activity/views.py
- templates/registration/login.html
- templates/registration/register.html
When a user wants to register, we verify if the username of email already exist. If so, we show an error message.
Verify if there is a user with the given email as well as the username given during registration.
-
ACT-108
> ACT-108 : If I am already a registered user, I receive an error page

- static/css/app.css
- templates/base.html
- templates/index.html
- templates/indicators/data_report.html
- Update fonts: Header: Inconsolata; body: Lato
- Updated font family for all heading tags and the body to the expected ones
@odenypeter 
[ACT-94](https://hikaya.atlassian.net/browse/ACT-94)
> ACT-94 Update Nav and Body Font Family

- adminreport/templates/admin/change_list_results.html
- static/css/app.css
- templates/base.html
- templates/formlibrary/training_list.html
- templates/indicators/collected_data_table.html
- templates/indicators/program_indicators_table.html
- templates/workflow/programdashboard_list.html
- transform all tables to data tables
- Added `id` prop to tables and initialised tables as `DataTable`s (`$('#id').DataTable()`)
@odenypeter @Ismailhachimi @AkshJain99 
[ACT-99](https://hikaya.atlassian.net/browse/ACT-99)
> ACT-99 All tables to DataTables

- templates/registration/profile.html
Resloving the padding layout of Profile Page
@henryohanga
ACT-117
> Resloving the padding layout of Profile Page

- templates/workflow/stakeholder_form.html
Improved Padding for Stakeholders Form
@henryohanga @odenypeter 
ACT-125
> ACT-125 Improved Padding for Stakeholders Form

- formlibrary/forms.py
- formlibrary/models.py
- formlibrary/views.py
Unable to view Beneficiary record after saving
Check what data is used, and how we can adjust the form so that we can filter by wfl1 later
Do the same for distributions and trainingattendance models for listing by organization
ACT-147
> Act 147: Unable to view Beneficiary record after saving

- reports/templates/report.html
- static/css/app.css
- templates/base.html
- templates/components/objectives.html
- templates/customdashboard/program_list.html
- templates/formlibrary/beneficiary_list.html
- templates/formlibrary/distribution_list.html
- templates/formlibrary/training_list.html
- templates/index.html
- templates/indicators/collecteddata_list.html
- templates/indicators/data_report.html
- templates/indicators/disaggregation_report.html
- templates/indicators/filter.html
- templates/indicators/indicator_list.html
- templates/indicators/report.html
- templates/indicators/tva_report.html
- templates/workflow/contact_list.html
- templates/workflow/documentation_list.html
- templates/workflow/level1.html
- templates/workflow/projectdashboard_list.html
- templates/workflow/report.html
- templates/workflow/site_profile_list.html
- templates/workflow/stakeholder_list.html
- add breadcrumbs to all visible pages
- Styled the breadcrumb to suite UI guidelines
- updated breadcrumbs on every visible page
[ACT-112](https://hikaya.atlassian.net/browse/ACT-112)
> ACT-112 Add Breadcrumbs to Pages

- formlibrary/views.py
- templates/components/objectives.html
- templates/formlibrary/beneficiary_list.html
- templates/formlibrary/beneficiary_modal_form.html
- templates/indicators/add_indicator_modal.html
- templates/indicators/indicator_list.html
- templates/workflow/add_project_modal.html
- templates/workflow/contact_form.html
- templates/workflow/contact_list.html
- templates/workflow/documentation_list.html
- templates/workflow/level1.html
- templates/workflow/modals/add_document_modal.html
- templates/workflow/program_projects_table.html
- templates/workflow/projectagreement_list.html
- templates/workflow/projectdashboard_list.html
- templates/workflow/stakeholder_list.html
A number of layout and CRUD fixes
> ACT-165 Layout Fixes

- templates/workflow/documentation_form.html
- templates/workflow/documentation_list.html
- templates/workflow/modals/add_document_modal.html
- workflow/models.py
Change references of Documentation to Documents 
Changed references of Documentation to Documents
[ACT-202](https://hikaya.atlassian.net/browse/ACT-202)
> ACT-202: Change references of Documentation to Documents

- static/js/auth/user_register.js
- templates/registration/register.html
User Registration: Make "First Name" required
Made "First Name" required
Added input validation for first name
[ACT-221](https://hikaya.atlassian.net/browse/ACT-221)
> ACT-221: User Registration: Make "First Name" required

- templates/workflow/site_profile_list.html
Change references of Site Profile to Locations
Enhance locations page
@odenypeter 
[ACT-201](https://hikaya.atlassian.net/browse/ACT-201)
> ACT-201: Enhance locations page

- templates/base.html
- templates/workflow/site_profile_list.html
- templates/workflow/site_profile_map.html
- templates/workflow/siteprofile_form.html
- workflow/urls.py
- workflow/views.py
- Break the site profiles listing page into list and map pages
- introduced a url argument `display` that shows when to list or show the map
@odenypeter 
[ACT-218](https://hikaya.atlassian.net/browse/ACT-218)
> ACT-218 Separate Site Profiles Listing and Map

- formlibrary/urls.py
- formlibrary/views.py
- templates/admin/user_invite_modal.html
- templates/formlibrary/distribution_form.html
- templates/formlibrary/distribution_list.html
- templates/formlibrary/modals/add_distribution_modal.html
- templates/formlibrary/modals/add_training_modal.html
- templates/formlibrary/training_list.html
- templates/indicators/add_indicator_modal.html
- templates/workflow/add_project_modal.html
- templates/workflow/modals/add_document_modal.html
- templates/workflow/modals/add_stakeholder_modal.html
- Quick entry form for the training form
- Quick entry form for the distribution form
@odenypeter 
[ACT-216](https://hikaya.atlassian.net/browse/ACT-216)
> ACT-216 Quick Entry Modals for Training and Distribution Form

- static/css/app.css
- static/css/components.css
- templates/admin/landing_page.html
Admin Dashboard (Organization Settings) UI fixes
Removed border radius on active tab border
Removed button options on usage tab sub-navigation
@odenypeter 
[ACT-219](https://hikaya.atlassian.net/browse/ACT-219)
> ACT-219: Admin Dashboard (Organization Settings) UI fixes

- templates/base.html
Update Main App Navigation in the UI
Updated main app navigation in the UI
@odenypeter 
[ACT-252](https://hikaya.atlassian.net/browse/ACT-252)
> ACT-252: Update Main App Navigation in the UI

- templates/components/objectives.html
- templates/customdashboard/program_list.html
- templates/indicators/indicator_list.html
- templates/workflow/contact_list.html
- templates/workflow/level1.html
- templates/workflow/projectdashboard_list.html
- templates/workflow/site_profile_list.html
Update all sub-header text for List Pages
Updated all sub-header text for List Pages
@odenypeter 
[ACT-250
](https://hikaya.atlassian.net/browse/ACT-250)
> ACT-250: Update all sub-header text for List Pages

- static/css/components.css
Briefly describe what the PR addresses
Removed side nav items border radius
[TOLA-219](https://hikaya.atlassian.net/browse/ACT-219)
> ACT-219: Remove side nav items border radius

- static/css/components.css
UI clean up
Removed margin between sub navigation options
[ACT-219](https://hikaya.atlassian.net/browse/ACT-219)
> ACT-219: UI clean up

- templates/indicators/objective_update_form.html
- templates/workflow/projectagreement_form.html
Update breadcrumbs
Updated breadcrumbs
[ACT-251](https://hikaya.atlassian.net/browse/ACT-251)
> ACT-251: Update breadcrumbs

- templates/shared/level1_modal_form.html
- When creating a program, the whole page is loaded back as the response. This is a fix to this issue
- Updated the submit url to `/dashboard/0/`
@odenypeter 
[ACT-238](https://hikaya.atlassian.net/browse/ACT-283)
> ACT-238 Fix Success Toast Response

- activity/views.py
- static/css/hikaya-bootstrap.css
- templates/index.html
- templates/workflow/site_profile_map.html
Fix locations map breadcrumbs
[ACT-274](https://hikaya.atlassian.net/browse/ACT-274)
> ACT-274 update locations map breadcrumbs

- activity/views.py
- formlibrary/forms.py
- formlibrary/views.py
- static/css/app.css
- templates/formlibrary/distribution_form_tab_ui.html
- templates/formlibrary/form-sections/distribution/additional_info.html
- templates/formlibrary/form-sections/distribution/details.html
- templates/formlibrary/form-sections/distribution/participants.html
Merge Distribution form into Tab UI
Display the individual cryspy form fields instead of the entire form
Wrap bootstrap tab inside the form
Create a template for each of the section
Have a common submit button (action section)
@IvyMMutiso 
ACT-212
> Distribution form tab ui

- static/css/app.css
Standardise the pagination buttons to the size of `btn-sm`
@odenypeter 
[ACT-281](https://hikaya.atlassian.net/browse/ACT-281)
> ACT-128 Update pagination buttons

- formlibrary/forms.py
- static/css/app.css
- templates/formlibrary/form-sections/training/additional_info.html
- templates/formlibrary/form-sections/training/details.html
- templates/formlibrary/form-sections/training/participants.html
- templates/formlibrary/trainingattendance_form.html
Update Training Attendance create form with Tabs in UI
Training form tabs UI
@odenypeter 
[ACT-210](https://hikaya.atlassian.net/browse/ACT-210)
> ACT-210: Add tabs to training form

- static/css/app.css
- templates/base.html
Fix user dropdown when on small screens
@odenypeter 
[ACT-316](https://hikaya.atlassian.net/browse/ACT-316)
> ACT-316 Fix User Dropdown Issues on Small Screens

- templates/base.html
- templates/workflow/project_form_tab_ui.html
- workflow/forms.py
- workflow/views.py
Fix
- Program label
- Close button
> ACT-234 Fix Programs Label and Close Button for Edit Project Form

- static/css/hikaya-bootstrap.css
- templates/shared/level1_modal_form.html
- Add save & new button to program quick action
[ACT-302](https://hikaya.atlassian.net/browse/ACT-302)
> ACT-302 Add Save and New Program Quick Entry

- activity/settings/test.py
Set up unit tests
Add tests configuration, tests folder and __init__.py files
ACT-352
> set up unit test

- activity/views.py
Prevent users from registering multiple account with the same email address and different cases
Always convert the email to lower-case during registration and login
All good
@henryohanga @IvyMMutiso @ninetteadhikari 
ACT-388
> ACT-388:- Prevent duplicate mails

- .github/workflows/activity_ci_cd.yml
- activity/views.py
- requirements.txt
- templates/indicators/indicator_form_tab_ui.html
- templates/indicators/objective_update_form.html
- templates/workflow/contact_form.html
- templates/workflow/program-form-sections/program_access.html
- workflow/forms.py
Fix various minor issues raised by @andrewtpham 
@IvyMMutiso @ninetteadhikari @henryohanga 
ACT-394, ACT-395, ACT-396, ACT-397, ACT-398, ACT-402, ACT-407
> Minor HotFixes

- indicators/forms.py
- indicators/models.py
- indicators/urls.py
- indicators/views.py
- templates/indicators/collecteddata_form.html
Fix indicator hot fixes
@IvyMMutiso @ninetteadhikari 
ACT-415, ACT-416
> Indicator hot fixes

- activity/util.py
- customdashboard/views.py
- scripts/get_data.py
- workflow/migrations/0001_initial.py
remove all remaining instances of MC
Replace all  the mc tied emails and urls in the codebase to hikaya
None
@IvyMMutiso @ninetteadhikari 
ACT-409
> ACT-409:- Remove All Remaining Instances of MC

- activity/util.py
- customdashboard/views.py
- scripts/get_data.py
- static/js/auth/org_register.js
- workflow/migrations/0001_initial.py
Replace all spaces in the organization name with spaces when creating the organization url during org registration
Use the JavaScript global replacement syntax
None
@IvyMMutiso @ninetteadhikari 
ACT-422
> Fix Org Url on Org Registration Form

- static/js/admin.js
- templates/components/modals/add_objective_modal.html
- templates/formlibrary/beneficiary_modal_form.html
- templates/index.html
- templates/shared/level1_modal_form.html
- templates/workflow/add_project_modal.html
- templates/workflow/documentation_list.html
- templates/workflow/level1.html
- templates/workflow/modals/add_document_modal.html
- templates/workflow/program_form_tab_ui.html
- workflow/forms.py
Remove hard coded programs and projects to WFL1 and WFL2 labels
Remove extra 's' from WFL2 name
Invitation toast message typo
Removed hard coded programs and projects to WFL1 and WFL2 labels
Removed extra 's' from WFL2 name
Fixed Invitation toast message typo
@odenypeter 
[ACT-414](https://hikaya.atlassian.net/browse/ACT-414)
> ACT-414: Rename labels

- activity/views.py
- indicators/views.py
- templates/admin/invalid_invitation.html
Invalidate invitation link when revoked
Check if the invitation link is still valid before displaying the registration form.
None
@shinroo @IvyMMutiso @ninetteadhikari 
ACT-424
> ACT-424:- Invalidate the Invitation Link When Revoked

- indicators/forms.py
- indicators/views.py
- workflow/forms.py
- workflow/views.py
Update level 1 and level 2 labels
Updated level 1 and level 2 labels
@odenypeter 
[ACT-414](https://hikaya.atlassian.net/browse/ACT-414)
> ACT-414: Update level 1 and level 2 labels

- templates/admin/default_settings.html
Organization Settings Configuration form has incorrect labels attribute
Fixed Organization Settings Configuration form labels attribute
Updated ids to match 
[ACT-423](https://hikaya.atlassian.net/browse/ACT-423)
> ACT-423: Fix Organization Settings Configuration form labels attribute

- templates/workflow/program_projects_table.html
- templates/workflow/projectdashboard_list.html
Project: In Project List view, remove Form Version and add Program associated to the project
Projects list view improvements
@andrewtpham @ninetteadhikari @odenypeter 
[ACT-399](https://hikaya.atlassian.net/browse/ACT-399)
> ACT-399: Projects list view improvements

- templates/registration/login.html
- templates/registration/register.html
Login and Registration pages are using "Close" and "Submit" buttons with the wrong label
Review login and registration pages buttons labels
[ACT-435](https://hikaya.atlassian.net/browse/ACT-435)
> ACT-435: Review login and registration pages buttons labels

- static/js/admin.js
- templates/admin/default_settings.html
Organization Settings Configuration form does not have validation for Empty labels
Added form validation for the organization settings configuration form
@odenypeter 
[ACT-427](https://hikaya.atlassian.net/browse/ACT-427)
> ACT-427: Validate organization settings configuration form

- templates/base.html
- templates/workflow/modals/add_site_modal.html
Replace SiteProfile Add Location Map on Modal with OSM + Leaflet.js
- updated versions of js and css dependencies for leaflet.js in base.html
- adapted POC from ACT-408 to render map on modal and interface with crispy form by updating templates/workflow/modals/add_site_modal.html
- The map is not responsive, but I believe this should be addressed in a separate ticket
- The CRUD for this modal did not work when I tested on my branch
ACT-335
> ACT-335: added map to modal, modified base.html to include updated leaflet js and css dependencies

- templates/workflow/level1.html
WFL1/program list page: Direct user to dropdown item page
Direct user to dropdown item page (wfl1 list)
@odenypeter 
[ACT-412](https://hikaya.atlassian.net/browse/ACT-412)
> ACT-412: Direct user to dropdown item page

- templates/indicators/form-sections/performance.html
Indicator: Remove additional disaggregation field
Removed additional disaggregation field
@odenypeter @shinroo 
[ACT-400](https://hikaya.atlassian.net/browse/ACT-400)
> ACT-400: Remove disaggregation field

- static/bootstrap/css/bootstrap.css
- static/css/app.css
- static/css/hikaya-bootstrap.css
Updated CSS for `Close`, `Save`, and `Save & New` buttons
updated hikaya-css file
None
@IvyMMutiso @ninetteadhikari 
ACT-470
> ACT-470: updated css for buttons

- static/css/app.css
- templates/workflow/modals/add_site_modal.html
Make map on add site modal responsive
Made map on add site modal responsive
@odenypeter 
[ACT-465](https://hikaya.atlassian.net/browse/ACT-465)
> ACT-465: Make map on add site modal responsive

- CONTRIBUTING.md
Updated contribution readme
Added section on development process
this is a new PR and pulled from the `dev` branch
@odenypeter 
ACT-475
> ACT-475 update contribution readme

- indicators/urls.py
- indicators/views.py
- templates/base.html
- templates/components/levels.html
Perform CRUD on Level: Add level Listing Page
Create a get view for levels
Create a list HTML page.
I set the number of characters displayed on the levels table on the UI to 50, same for the name. 
@andrewtpham 
@odenypeter 
[ACT-377](https://hikaya.atlassian.net/browse/ACT-377)
> Act 377 : Add level Listing Page

- indicators/urls.py
- indicators/views.py
- templates/base.html
- templates/components/levels.html
- templates/components/modals/add_level_modal.html
Perform CRUD on Level: Add level Create a modal form
Create a post view for levels
Create a modal form for capturing level data
There are some fields missing on the level's model. @andrewtpham  said he will create another ticket to add those fields then add the required changes to the level creation process.
@andrewtpham 
@odenypeter 
[ACT-375](https://hikaya.atlassian.net/browse/ACT-375)
> Act 375: Add level create form

- templates/small_site_profile_map.html
Replace map on dashboard with OSM + leaflet.js
Duplicated map from site profile map template onto small site profile map template.
Added `zoomSnap: 3` to map constructor altering the function of the fitBounds() function
The code should be refactored into a callable function stored in static js. I will address this in a separate card.
@andrewtpham @odenypeter 
ACT-480
> ACT-480: Replace map on dashboard with OSM + leaflet.js

- templates/workflow/siteprofile_form.html
Change the map on the siteprofile_update page to OSM + Leaflet.js
Inspected ids of generated crispy form elements, modified existing map script from site profile add modal to interact with the correct elements in the crispy form
As mentioned in ACT-480, I'd like to refactor all the map JS into the static structure that already exists to remove duplicate code.
@andrewtpham @odenypeter 
ACT-481
> Act 481: Change Site Profile Update Page Map to OSM + Leaflet.js

- static/css/app.css
- static/css/hikaya-bootstrap.css
- templates/indicators/add_collecteddata_modal.html
- templates/indicators/collected_data_table.html
- templates/workflow/program_projects_table.html
- templates/workflow/site_profile_list.html
Change "Collected Data" to "Results"
Changed "Collected Data" to "Results"
@odenypeter 
[ACT-504](https://hikaya.atlassian.net/browse/ACT-504)
> ACT-504: Change "Collected Data" to "Results"

- indicators/views.py
- static/js/collectdata.js
- templates/indicators/add_collecteddata_modal.html
None
@andrewtpham @odenypeter 
[ACT-513](https://hikaya.atlassian.net/browse/ACT-513)
> ACT-513: Update Date Collected field to be consistent with the application. 

- activity/util.py
- activity/views.py
- templates/admin/component_admin.html
- templates/admin/form_library_settings.html
- templates/admin/workflow_settings.html
Review organization settings UI
Review organization settings UI
@odenypeter
> Review organization settings UI

- indicators/views.py
- templates/indicators/level_update_form.html
Unable to "Close" button after editing a Level record
Reviewed close button functionality for the level update form
@odenypeter 
[ACT-515](https://hikaya.atlassian.net/browse/ACT-515)
> ACT-515: Review close button functionality for the level update form

- templates/workflow/siteprofile_form.html
- workflow/forms.py
- workflow/models.py
- fixed `save` and `close` buttons
- fixed map to reload on initial tab ui (fixed map loading issue)
- added `approved` to project status
changes files in form.py and the html template
N/A
@Kimaiyo077 @odenypeter 
ACT-522, ACT-523
> ACT-522 and ACT-523

- __init__.py
- templates/workflow/modals/add_site_modal.html
- templates/workflow/site_profile_list.html
- templates/workflow/site_profile_map.html
Fixes the bug that was present in map view of sites where the add location button was not functioning as expected.
None
@odenypeter @shinroo 
[ACT-486](https://hikaya.atlassian.net/browse/ACT-486)
> ACT-486: Fix add location button on site map display

- README.md
updated README
Briefly describe the approach used to address the issue
ACT-534
> ACT-534: update readme

- indicators/serializers.py
- indicators/views.py
- static/vue.js/collected_data_table.js
- templates/indicators/collected_data_table2.html
- templates/indicators/indicator_list.html
Migrated collected data table to vuejs
Refactored the collected data table endpoint to return json for easier processing on VueJs.
There's  a lot of unused code from the previous html template. I've opted not to delete it till clarification about it's use is given.
@andrewtpham @odenypeter 
[ACT-524](https://hikaya.atlassian.net/browse/ACT-524)
> refactor: Migrate collected data table to Vuejs

- activity/urls.py
- activity/views.py
Rewrite user login view to a class-based view
changed the function view to a class-based view
No
@odenypeter
[ACT-474](https://hikaya.atlassian.net/browse/ACT-474)
> ACT 474: Rewrite user_login view

- activity/urls.py
- activity/views.py
Rewrite register_organization view
changed the function view to a class-based view
No
@odenypeter
[ACT-473](https://hikaya.atlassian.net/browse/ACT-473)
> ACT 473: Rewrite register_organization view

- README.md
Update README.md file with instructions on how to install dependencies on Windows
None
@andrewtpham @ninetteadhikari 
[ACT-517](https://hikaya.atlassian.net/browse/ACT-517)
> ACT-517: Update Readme file with setup instructions for Windows users

- workflow/forms.py
Fixes bug where location disappears from the list after being updated
Add organizations field to the exclusion list in the update form
None
@odenypeter @IvyMMutiso 
ACT-516
> ACT-561: Fix bug when updating a site

- CONTRIBUTING.md
Updates contribution file
Update contribution file
None
@andrewtpham 
ACT-518
> ACT-518: Update contribution file

- indicators/views.py
- static/vue.js/indicators/data_collection_frequency.js
- templates/admin/indicator_configs/forms/data_collection_form.html
Data collection frequency: add 'Description' field
Added 'Description' field to Data collection frequency
@odenypeter @Kimaiyo077 
[ACT-554](https://hikaya.atlassian.net/browse/ACT-554)
> ACT-554:  Add 'Description' field to Data collection frequency

- indicators/views.py
- static/css/vue_tree.css
- static/vue.js/objectives_tree.js
- templates/base.html
- templates/components/objectives-tree.html
- templates/ui-components/vue_tree.html
Add objectives tree to objectives tree view
Created a custom vue component and integrated it into the view.
@odenypeter 
@andrewtpham 
[ACT-157](https://hikaya.atlassian.net/browse/ACT-157)
> Add vue tree component to objectives tree view

- indicators/serializers.py
- indicators/urls.py
- indicators/views.py
- static/vue.js/indicators/indicator_type.js
Refactor APIs to use DRF API views
Use DRF based API views to reduce the number of lines of code.
> IndicatorType APIs code refactor

- CONTRIBUTING.md
- README.md
- updated README and CONTRIBUTING files
- fixed typos
- added URLS
N/A
@Kimaiyo077 
ACT-517
> ACT-517-patch

- static/vue.js/indicators/indicator_type.js
- templates/admin/indicator_configs/lists/indicator_types_list.html
Showed messages when no indicator types in DB
Added a messages if indicator types are empty
ACT-580
> ACT-580 Showed messages when no indicator types in DB

- templates/formlibrary/beneficiary_form.html
- templates/formlibrary/distribution_form.html
- templates/formlibrary/trainingattendance_form.html
Show beneficiary, attendance and training forms
Show beneficiary, attendance and training forms
@Kimaiyo077 
[ACT-592](https://hikaya.atlassian.net/browse/ACT-592)
> ACT-592: Show beneficiary, attendance and training forms

- CONTRIBUTING.md
- NOTICE.md
add NOTICE.md file
added file to root folder
N/A
@ninetteadhikari 
N/A
> add notice file

- activity/views.py
Fixed login
iexact is only meant to be used in query set not in authenticate method.
ACT-600
> ACT-600 Fixed login

- formlibrary/forms.py
Fix Restrict Office model by Organization
Fix  getting offices by the organization by updating the DistributionForm 
No
@odenypeter  @ninetteadhikari  @andrewtpham 
[ACT-549](https://hikaya.atlassian.net/browse/ACT-549)
> ACT: 549 -fix office get restriction by organization

- static/css/app.css
- templates/admin/component_configs/lists/fund_code_list.html
- templates/admin/component_configs/lists/office_list.html
- templates/admin/component_configs/lists/profile_types_list.html
- templates/admin/component_configs/lists/stakeholder_type_list.html
- templates/admin/indicator_configs/lists/collection_frequency_list.html
- templates/admin/indicator_configs/lists/indicator_types_list.html
- templates/admin/indicator_configs/lists/level_list.html
- templates/admin/no_data.html
Add note when there are no records to display
Add note when there are no records to display
@odenypeter @Kimaiyo077 @andrewtpham 
[ACT-604](https://hikaya.atlassian.net/browse/ACT-604)
> ACT-604: Add note when there are no records to display

- static/vue.js/workflow/program_fund_code.js
Link "+ Fund code" with the Fund Code using Vue: Create Modal
Changed add program fund code modal to a vue modal
@odenypeter 
[ACT-547](https://hikaya.atlassian.net/browse/ACT-547)
> ACT-547: Change add program fund code modal to a vue modal

- templates/workflow/site_profile_list.html
- workflow/views.py
ACT-563 Added site active/inactive filter
> ACT-563 Added site active/inactive filter

- workflow/forms.py
Add logic to filter profile types by organization (site profile edit form)
Filter profile types by organization
@Kimaiyo077 @andrewtpham 
[ACT-581](https://hikaya.atlassian.net/browse/ACT-581)
> Filter profile types by organization

- .github/workflows/activity_ci_cd.yml
> fix builds

- infrastructure/main.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
Adds configurations used to create infrastructure
Used terraform and digital ocean modules to create the configurations. Creates k8s cluster, database cluster, and database for the app.
Necessary variables in the config need to be added to respective CI tools
@andrewtpham @odenypeter @nasirhjafri 
ACT-602
ACT-608
ACT-609
> ACT-607: Add infrastructure configuration

- docker-deploy/Dockerfile
- docker-deploy/start_app.sh
Add docker config for deployment
Creates docker config for deployment, the image relies on a db that is set up by ACT-607
Should be run by the CI tool
@andrewtpham @odenypeter
ACT-602
ACT-607
ACT-609
> ACT-608: Add docker config for deployment image

- deployment_files/autoscaler
- deployment_files/cert-config/cert-issuer
- deployment_files/cert-config/cert-manager-0.12.0.yaml
- deployment_files/cert-config/cert-secret
- deployment_files/cert-config/certificate
- deployment_files/deployment
- deployment_files/ingress-config
- deployment_files/ingress-service.yaml
- deployment_files/man.yaml
- deployment_files/metrics-server.yaml
- deployment_files/service
Add configs files used to deploy the app
Create templates used to deploy the app to k8s server. The templates use variables that are replaced by the CI to deploy.
Should be run by the CI tool
@andrewtpham @odenypeter
ACT-607
ACT-608
ACT-609
> ACT-602: Add config files used for deployment

- static/css/app.css
- templates/base.html
- main nav styling
- footer styling
- body links styling
modified app.css and base.html
N/A
@ninetteadhikari 
ACT-682
> ACT-682: styling

- .travis.yml
- ci-scripts/create_infrastructure.sh
Fix branches refrenced in build stage
Fix Travis CI and GH Actions configs
None
@odenypeter 
N/A
> ACT-609: Add configuration for travis CI

- templates/admin/component_admin.html
- templates/admin/workflow_settings.html
Moves the Fund code from the Components to Workflow tab in Organization setting
Moved the component
None
@andrewtpham @Kimaiyo077 
ACT-687
> ACT-687 Moves fund code to workflow tab

- activity/views.py
Fixed error on .get
.get raises an error when the object doesn't exist
closes #328 
@andrewtpham @odenypeter  @michaelbukachi Please review
> Issue #328 Fixed error on .get

- activity/views.py
Change organization logo update banner color
Fix organization logo update notification
@Kimaiyo077 
[ACT-717](https://hikaya.atlassian.net/browse/ACT-717)
> ACT-717: Fix organization logo update notification

- .github/workflows/activity_ci_cd.yml
- .travis.yml
Add config to notify slack upon deployment 
Add bash script that sends payload via curl to a Slack channel dedicated for slack notifications
None will be run by CI tools
@andrewtpham  @odenypeter @nasirhjafri 
ACT-695
> ACT-695: Add config for slack notification on deployment

- static/css/app.css
Add margin to the top of the `body`, below Nav bar
Adds margin
None
@andrewtpham 
None
> added margin below nav bar

- static/vue.js/collected_data_table.js
fix edit result modal to show evidence
fix edit result modal to show evidence
None
@andrewtpham 
ACT-728
> ACT-728: fix edit result modal to show evidence

- templates/registration/login.html
- templates/registration/register.html
Removes activity logo from login and registration page
Removes the img tag
None
@odenypeter @Kimaiyo077 
None
> Removes logo from login/registration

- CONTRIBUTING.md
Adds story point label to Contributor readme
--
Similar changes on story point labeling needs to be made in the team wiki https://github.com/hikaya-io/wiki/blob/master/start/development-process.md
@andrewtpham 
None
> Updates contributor readme

- static/vue.js/components/documents.js
Fix the error that arises when getting a list of programs.
Update URL for getting programs to the updated one. 
Fix success message by removing the response object.
None
@andrewtpham 
> Fix getting programs when adding a document

- static/css/app.css
- templates/indicators/collected_data_table2.html
Reverts "ACT-732 - Align table data"
> Revert "ACT-732 - Align table data"

- ci-scripts/notify_slack.sh
Fix issues on builds failing on build and test and deploy
Add conditions in main to run the functions of the branches meet the conditions
None
@odenypeter @andrewtpham @nasirhjafri 
None
> ISS-465: Fix failing builds on deploy stage

- indicators/urls.py
- indicators/views.py
- static/vue.js/collected_data_table.js
- static/vue.js/indicators/target_period.js
- templates/indicators/indicator_confirm_delete.html
- templates/indicators/indicator_list.html
add delete functionality for indicators
remove `console logs` in the code
Added new modal for confirming deleting an indicator
Update URLs and views to delete an indicator,
None
@andrewtpham 
#497
> ACT-497: add delete functionality for indicators

- .github/workflows/activity_ci_cd.yml
- ci-scripts/build_docker_image.sh
- ci-scripts/create_infrastructure.sh
- ci-scripts/deployment.sh
- ci-scripts/notify_slack.sh
Fix release not triggering the build
Add fix for Travis to build on releases
Config builds on prod to work on events rather than branch
None
@andrewtpham @odenypeter @nasirhjafri 
None
> ACT-693: Fix builds not triggering on release

- CONTRIBUTING.md
- updated contribution file and removed redundancies
- added development process section
- added navigating our repos section
@Kimaiyo077 @sannleen @ninetteadhikari 
> update contribution file + add dev process

- .github/workflows/activity_ci_cd.yml
- ci-scripts/create_infrastructure.sh
- deployment_files/autoscaler
- deployment_files/deployment
- infrastructure/main.tf
- infrastructure/variables.tf
Add resource tagging
update number of replicas to be added as variables
Add configs to add tags to resources. convert the minimum replica number and maximum replica numbers to variables
None
@odenypeter @nasirhjafri @andrewtpham 
None
> Add resource taging

- ci-scripts/build_docker_image.sh
- requirements.txt
Fix build image error
Use a lower version of the pendulum
set build script to stop when an error occurs in build process
None
@odenypeter 
None
> ISS-620: Fix build image error on build image stage

- ci-scripts/build_docker_image.sh
Fix a build failing in forked repos
Add conditions to the auth function to restrict the branches to run on. 
None
@odenypeter @sannleen 
None
> ISS-465: Fix build fail on build image stage in forked repos

- .gitignore
- activity/settings/local-sample.py
- activity/urls.py
- static/css/app.css
- templates/404.html
- templates/500.html
- templates/base.html
- templates/locale/fr/LC_MESSAGES/django.po
Resolve issues raised by #608 
1. The improper centering was due to the text below the images being large. This was resolved by simply removing the last word of the sentence in the middle, and putting it in the third line.
2. For the logo, I changed the reference to the image from `{{ STATIC_URL }}/img/...` to `static/img/...`. I can't pinpoint exactly why the old code was not working, especially that it is working fine with the 404 page.
3. Fixing the footer WIP
@ninetteadhikari @odenypeter 
#608
> Improve formatting of the 500 error page

- activity/settings/local-sample.py
Fix issue with styles not loading in dev
Set back debug to True
None
@Kimaiyo077 @andrewtpham @TAnas0 
None
> Fix style issue on dev

- static/vue.js/indicators/target_period.js
Fixes issue  #638 where target column in indicator list is not updating
until refresh
Refreshing the page right after updating the data
None
@andrewtpham 
#638
> fix: target column in indicator list not updating

- ci-scripts/build_docker_image.sh
- ci-scripts/create_infrastructure.sh
- ci-scripts/deployment.sh
- ci-scripts/notify_slack.sh
Update default branch 
Update default branch from dev to develop
None
@Kimaiyo077 @andrewtpham 
> Update default branch from dev to develop

- .github/workflows/activity_ci_cd.yml
- .travis.yml
- ci-scripts/build_docker_image.sh
- ci-scripts/deployment.sh
- ci-scripts/images/deploy-image/Dockerfile
- deployment_files/deployment-vault
- deployment_files/service_account
- deployment_files/token_review_srv_acc
- docker-deploy/start_app.sh
Pass secrets securely to deployments without building the image with secrets
Setup vault server
Read secrets from vault server into the application to be deployed
None
@odenypeter @andrewtpham @Kimaiyo077 
None
> Implement secrets injection with vault

- formlibrary/models/inventory.py
Implement inventory model for form library.
Made one file called inventory.py and built out the fields.
I wasn't 100% how to assign a label for the total property. If anyone knows how to do that help would be very appreciated!
418
> Inventory model

- workflow/tests/test_workflow_models.py
Added tests for Stakeholder model in workflow. 
Followed other tests for models and made sure to have all lines covered. 
The tests are located in tests/test_workflow_models.py
#584
> Stakeholder Tests

- static/css/app.css
- templates/indicators/collected_data_table2.html
Fixes issue 674
There was a cell only being added sometimes (which meant no consistency in alignment of buttons) so I created an empty cell for when it wasn't needed otherwise. 
No
674
> Issue 674 

- requirements.txt
Reverts hikaya-io/activity#741
> Revert "Build(deps): Bump django-debug-toolbar from 1.11 to 1.11.1"

- .github/workflows/activity_ci_cd.yml
- ci-scripts/build_docker_image.sh
Use the new Digitalocean container registry in CI scripts and Github Actions
Added a secret with the DO access token
@andrew @ninetteadhikari 
None
> feat(CI): update Docker credentials and Docker image names

- .github/workflows/activity_ci_cd.yml
- ci-scripts/build_docker_image.sh
Reverts hikaya-io/activity#781
> Revert "feat(CI): update Docker credentials and Docker image names"
