hikaya-io/activity

workflow/views.py

Change WFL2 listing (project) in the "Reports/WFL2 Report" page to filter by organization and selected WFL1 and not country.
Check transmitted data in workflow Report and ReportData views.
-
@henryohanga @odenypeter
ACT-106

ACT-106 : Change WFL2 listing page to filter by Organization/Active level1 and not Country

---

customdashboard/views.py
indicators/views.py
workflow/views.py

Change Indicators listing page to filter by Organization/Active level1 and not Country
Checking the related views.
The filters in most of "Reports/" pages don't work as "Reports/WFL2 Report". Their UI style too.
@odenypeter 
ACT-107

Act 107 : Change Indicators listing page to filter by Organization/Active level1 and not Country

---

indicators/admin.py
indicators/models.py

There is a mix up of the admin models code inside the `models.py` file for indicator app. All admin models should be present only in the `admin.py` file.
None
@odenypeter 
[ACT-431](https://hikaya.atlassian.net/browse/ACT-431)

ACT-431:- Clean up Indicators app admin models

---

formlibrary/admin.py
formlibrary/models.py

There is a mix up of the admin models code inside the `models.py` file for the Form-Library app. All admin models should be present only in the `admin.py` file.
None
@odenypeter 
[ACT-438](https://hikaya.atlassian.net/browse/ACT-438)

ACT-438: Clean up admin models in the form library app

---

indicators/urls.py

Updates Indicator app URLs to use `path` 
None
@odenypeter 
[ACT-440](https://hikaya.atlassian.net/browse/ACT-440)

ACT-440: Update indicator urls to use path

---

activity/urls.py

Updates Activity app URLs to use `path` 
None
[ACT-441](https://hikaya.atlassian.net/browse/ACT-441)

ACT-441: Clean up Activity app URLs

---

templates/workflow/site_profile_map.html

To replace the map shown on the siteprofile map view under the workflows section with an OSM map rendered by leaflet.js
Requirements:
- display all sites on the map
- autozoom to correct level such that all sites are visible
- each site should link to its own page for editing
Repurpose django template loop used by Google maps implementation (over the get_site_profile variable)
Research Leaflet.js autozoom: https://stackoverflow.com/questions/16845614/zoom-to-fit-all-markers-in-mapbox-or-leaflet
Research Leaflet.js links: https://github.com/Leaflet/Leaflet.markercluster/issues/486
Replace JS code in site_profile_map.html template accordingly
None, the map was also already responsive but maybe Ivy should take a look just to make sure its up to scratch? (I did not need to write any CSS for …

ACT-455: Replace SiteProfile Map View with OSM + Leaflet.js

---

indicators/urls.py
indicators/views.py
static/js/collectdata.js
templates/indicators/add_collecteddata_modal.html
templates/indicators/indicator_list.html

- Added quick action modal for adding actuals for specific indicators. The form also has field validations for required fields and `save and new` button that saves and resets the form for data to be added again for the same indicator.
None
[ACT-342](https://hikaya.atlassian.net/browse/ACT-342)
[ACT-343](https://hikaya.atlassian.net/browse/ACT-343)
[ACT-468](https://hikaya.atlassian.net/browse/ACT-468)

ACT-342: Add modal for adding collected data

---

static/js/collectdata.js
templates/indicators/collected_data_table.html

Update `add collected data` button to open a modal instead of opening a different page to enter the collected data.
Remove existing links and replace them with `<button>` and relevant attributes to open the modal correctly
None
@odenypeter 
ACT-342

Fix 'add collected data' button to open modal instead of separate page

---

indicators/views.py

After deleting an objective record, the page needs to be redirected to the Objective List Page
Review objective delete logic
@odenypeter 
[ACT-510](https://hikaya.atlassian.net/browse/ACT-510)

ACT-510: Review objective delete logic

---

requirements.txt

To fix Potential SQL injection via tolerance parameter in GIS functions and aggregates on Oracle https://docs.djangoproject.com/en/3.0/releases/2.2.11/

Bump django version to 2.2.11

---

templates/base.html

I fixed the 'Hikaya' footer link to lead to the Hikaya homepage
I simply saw that the link went to a 404 so I swapped the link with the correct one.
Nope, no concerns at all. Simple HTML change in base.html
This address half of #295

fixed hikaya 404 link - now linking to hikaya homepage

---

.coveragerc
.coveralls.yml
.github/workflows/activity_ci_cd.yml
README.md
ci-scripts/run_tests.sh

Use codecov to report on code coverage
Add config to CI tools to send code coverage to codecov rather than coveralls. Fixes the coverage command to point to all project files omitting virtualenv files
Glitch with Travis not getting notifications on PR events or Push events. Need to test Codecov functionality with travis before the merge. It works well on GitHub actions

ACT-680[WIP]: Add config for coverage provision by codecov

---

Pipfile.lock
indicators/views.py
static/vue.js/collected_data_table.js
static/vue.js/indicators/target_period.js
templates/indicators/forms/target_period_form_footer.html
templates/indicators/forms/target_period_modal.html
templates/indicators/indicator_list.html

- Finish Update and delete functionality for target periods
- Updated Django view to enable delete and update multiple target periods.
- Update modal to be dynamically created with target periods if they exist and allow users to edit them.
- Delete target periods if they existed.
The create target periods' logic changed a bit. Please test the entire CRUD operation, from creating target periods to deleting them.
@andrewtpham @ninetteadhikari @IvyMMutiso 
ACT-683
ACT-557
ACT-722

ACT-683: Edit and Delete target periods Vue modal

---

templates/indicators/form-sections/targets.html

Fix the error that occurs when updating an indicator with existing target periods.
Change the check to expect the sum of targets instead of the overall target which already exists.
None
@andrewtpham 
ACT-731

ACT-731: Fix error when updating indicator data

---

.github/workflows/activity_ci_cd.yml
.travis.yml
ci-scripts/build_docker_image.sh
ci-scripts/create_infrastructure.sh
ci-scripts/deployment.sh
ci-scripts/notify_slack.sh
ci-scripts/run_tests.sh
docker-deploy/Dockerfile

What is the Purpose?
Add config to create staging image
Add config to deploy to staging cluster
Adds conditionals to deploy on branch staging
None
@andrewtpham 
@nasirhjafri 
@odenypeter 
None

ACT-692: Add config for staging cluster

---

CONTRIBUTING.md

- Updates branch naming convention from Jira to GitHub issue number

Updates Contribution md file

---

activity/tokens.py

Fix activation link invalid error when the link is accessed more than once. The invalid message only shows when the link has been manipulated
Only show invalid link when the token has been manipulated but always redirect to login when the token is valid
None
@odenypeter @andrewtpham @nasirhjafri 
None

ISS-437: Fix invalid link message

---

indicators/views.py
templates/indicators/form-sections/disaggregation.html

Fix JSON decoding error that occurs when trying to update an Indicator that has existing disaggregations.
Add a `JSON.stringfy` to the data being passed to the backend, this will allow the full object to be sent back and then decoded successfully by the backend. The previous implementation returned a representation of the object that could not be decoded in the backend.
None
@odenypeter @andrewtpham @TAnas0 
#482 
#455

ACT-482: Fix error when updating indicator data

---

static/vue.js/collected_data_table.js

Fix defect that occurs when trying to add a result after editing a different one.
After updating a result, the `currentResult` should be set to `null` to prevent affecting the next result to be entered
None
@andrewtpham 
#483

ACT-483: Fix defect that occurs after editing a result.

---

indicators/urls.py
indicators/views.py
static/vue.js/collected_data_table.js
static/vue.js/indicators/target_period.js
templates/indicators/indicator_confirm_delete.html
templates/indicators/indicator_list.html

Update staging with the fix for indicator delete that is on dev
Update staging with the fix for indicator delete that is on dev
This PR should not be squashed but rather use the normal merge so that commits on dev and staging are aligned
@sannleen @andrewtpham 

Update staging with fix for indicator delete

---

ci-scripts/build_docker_image.sh
ci-scripts/create_infrastructure.sh
ci-scripts/deployment.sh

Fix image failure build on staging
Fix ECHO error on staging stating that command is not found
None
@odenypeter @sannleen 
None

ISS-620: Fix image build error on staging

---

activity/settings/base.py

After a user is done registering, the confirmation email and any other email notification they receive should use the HTTPS protocol instead of HTTP for security.
set a variable in base.py that instructs the is_secure method to read https from our server and to trust the X-Forwarded-Proto header that comes from our proxy, and any time its value is 'https', then the request is guaranteed to be secure.
Test from activity-dev-tests.hikaya.dev
@Kimaiyo077 @TAnas0 
None

ISS-481: Fix host identification issue on links from server

---

.travis.yml

Fix doctl install error on travis, The error was causing deployments on travis to fail.
Update snapd before installing doctl to avoid error while job tries to fetch doctl
None
@Kimaiyo077 
None

Fix doctl install error

---

reports/views.py

Fixes issue #645 
The issue was coming from reports/views in the GenerateReport view, the total_targeted should be derived from the lop_target of an indicator instead of being added from the target periods being reported. Fixed this based on @Kimaiyo077 's comment
None
@Kimaiyo077 @andrewtpham 
#645

Fix: The "End of Program " column should use the Overall Target value

---

README.md

`python3` can point to different versions depending on what python3 defaults to on someone's OS. It's better if we pass the specific python version along with the `virtualenv` command to make sure we don't run into some unnecessary bugs.
Use `-p` provided by `virtualenv`
Fixes #651

docs: Add Python version in Virtualenv Command

---

.github/workflows/activity_ci_cd.yml
ci-scripts/build_docker_image.sh
ci-scripts/create_infrastructure.sh
ci-scripts/deployment.sh
deployment_files/autoscaler
deployment_files/deployment-vault
deployment_files/service
deployment_files/shared-ingress-config

Configure staging and dev to share resources
Destroy staging cluster and configure it to deploy to dev cluster
None
@andrewtpham @sannleen 

Optimize resources dev stag

---

deployment_files/deployment-vault

Fix deploy template error
Minimum pods were being read as a string rather than an integer.A variable replacement was not occurring before deployment
None
@andrewtpham 
None

Fix deploy template error

---

static/css/app.css
templates/emails/invite.html
templates/emails/registration/email_confirmation.html
templates/emails/registration/welcome.html
templates/registration/password_reset_done.html
templates/registration/password_reset_email.html

fix: remove preview text from email template
remove "MC_PREVIEW_TEXT" from the email template
None
@andrewtpham 
None

fix: remove preview text from email template

---

static/css/app.css

The footer would not stay at the bottom of the viewport if the content in the page was shorter than the viewport's height.
I gave the sibling element of the footer, a div with class `.activity-content` a `min-height: calc(100vh - 120px);`. This forces the `.activity-content` element to expand when the viewport is larger than the contents. It also allows the footer to sit normally at the bottom of the page when the content is larger than the viewport
```css
/* Push footer to bottom of page */
.activity-content {
min-height: calc(100vh - 120px);
}
```
After checking all of the pages in Activity, I found that the following two have a slightly different DOM layout, and so they are unaffected by this CSS change.
Workflows (from the top menu) > Projects - URL: …

ACT-435: Add sticky footer

---

Dockerfile

Fix the Docker build image step occuring on Github Actions: https://github.com/hikaya-io/activity/actions/runs/1158606024
Issue is during the PIP packages install, more specifically the `cryptography` package, which is not a direct dependency of ours (through `pendulum` package)
Since we are using `cryptography<3.5`, we can just disable the Rust build during the install using an environment variable: https://github.com/pyca/cryptography/issues/5771#issuecomment-775016788
The whole Github issue also addresses how to install Rust if we want to upgrade `cryptography`
None
@michaelbukachi 
None

Fix installation of `cryptography` PIP package in Docker build

---

Dockerfile
docker-deploy/Dockerfile

PR https://github.com/hikaya-io/activity/pull/752 was not successful. This is a revert of that PR and reimplementation of the bug fix
Edited the right Dockerfile used in deployment Bash script
@michaelbukachi @Kimaiyo077 
https://github.com/hikaya-io/activity/actions/runs/1158933148

refactor(CI): Move Docker commands to the right Dockerfile

---

.github/workflows/activity_ci_cd.yml

1. Since we moved to the new K8s cluster for Activity Dev, we don't need to trigger the deployment from our CI. We need this only for the legacy production cluster.
2. Configured Github Actions to ignore PRs limited to documentation and Markdown files, to avoid unnecessary GA runs
All edits are in the GA YAML file
None
@andrewtpham 
None

Disable deploy stage on `develop` branch

---

templates/admin/map_settings.html
templates/workflow/documentation_list.html
templates/workflow/projectdashboard_list.html

The footer for the project and documents page would not stay at the bottom of the page.
There was an unclosed `</div>` tag in `documentation_list.html` and an open `<table>` tag in `projectdashboard_list.html`
None
@andrewtpham @ninetteadhikari @TAnas0 
Issue #716

fixed sticky footer for project and documents page (issue #716)

---

templates/emails/registration/email_confirmation.html

Correct the link in the email confirmation email.
I suspect this to be breaking the Activity E2E tests
Replaced the link with the variables passed to the email template
Once deployed, do a manual check
None
None

fix(email): correct link in confirmation email

---

requirements.in
requirements.txt

This PR upgrades key dependencies with `critical` and `high` issues
This PR supersedes the dependabot PRs raised:
- https://github.com/hikaya-io/activity/pull/785
- https://github.com/hikaya-io/activity/pull/782
- https://github.com/hikaya-io/activity/pull/778
Pull the latest in this branch and perform spot checking and testing to see if the app is running locally.
@amosnjoroge @ninetteadhikari

upgrade dependencies
